site_name: Bijan Rahnamai

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

extra:
  generator: true
markdown_extensions:
  - attr_list
  - md_in_html

# Page tree
nav:
#  - Blog:
#      - America's National Parks: blog/2022-07-15-National-Parks.md
  - Art:
      - Shows: art/shows.md
  - Engineering:
      - Certifications: engineering/certifications.md
      - Learning From Failures: engineering/learning_from_failures.md
      - Software Delivery: engineering/software_delivery.md
  - Cool Experiences:
      - Skydiving: blog/skydiving.md
  - Home:
      - Home: index.md