site_name: Bijan Rahnamai

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

extra:
  generator: true
markdown_extensions:
  - attr_list
  - md_in_html

# Page tree
nav:
#  - Blog:
#      - America's National Parks: blog/2022-07-15-National-Parks.md
  - Engineering:
      - Certifications: engineering/certifications.md
  - Home:
      - Home: index.md