site_name: Bijan Rahnamai

theme:
  name: material
  favicon: assets/images/b-heart.png
  palette:
    primary: blue grey
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

extra:
  generator: true
markdown_extensions:
  - attr_list
  - md_in_html

# Page tree
nav:
#  - Blog:
#      - America's National Parks: blog/2022-07-15-National-Parks.md
  - Home: index.md
  - Art:
      - Shows: art/shows.md
#      - Recorded Music: art/recorded_music.md
  - Websites I Manage:
      - Austin Open Mic Poetry: websites_i_manage/austin_open_mic_poetry.md
      - My Friend Doug: websites_i_manage/my_friend_doug.md
  - Books:
      - Book Reviews: books/book-reviews.md
  - Engineering:
      - Certifications: engineering/certifications.md
      - Learning From Failures: engineering/learning_from_failures.md
      - Software Delivery: engineering/software_delivery.md
  - Cool Experiences:
      - Skydiving: cool_experiences/skydiving.md